### ISSUE TITLE
How can I disable bumpVersion?

### ISSUE THREAD

**Issue by StephanBijzitter** [renovateapp/config-help#11]
https://renovateapp.com/docs/configuration-reference/configuration-options#bumpversion
Our versions are managed strictly through Lerna through conventional commits.

As such, I do not ever want to see someone (or something) to change the version of a package in a pull request, since this is automatically done on master.

Would `bumpVersion: false` suffice?

**Comment by rarkins** [comment]
That’s strange - it should be disabled by default. Do you have any public example or can you email me logs from a private example?

**Comment by StephanBijzitter** [comment]
Ah, I dungoofed. Seems it's time for me to go to bed.

The config contained `"bumpVersion": "minor",` and I assume that I added that under the assumption that renovate would _always_ update the lockfile but only update the dependency version range (and now the package version) for minor updates.

Yup, everything working as expected.

**Comment by rarkins** [comment]
Yeah, stay clear of `bumpVersion` unless you definitely need it. Let me know if you want any help on configuring different behaviour for minor/major though.

**Comment by StephanBijzitter** [comment]
I just updated the config, ran renovate again locally and the pull requests were automatically rebased, this time without the version bumps.

Gotta say I'm very impressed with how the entire system runs (and the extremely easy way to self-host which is basically "install and run"). Though the documentation for all options is a bit overwhelming and as a result (at least to me) a bit chaotic.

I'll try it out some more and create a nice list of proper feedback later) Hopefully I can also find the time to submit a pull request for the documentation, if you were to agree with my assessment to come.

So far though, pretty nice!
