### ISSUE TITLE
LockFileMaintenance Documentation

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/config-help#13]
The Renovate documentation website shows the [`lockFileMaintenance`](https://renovateapp.com/docs/configuration-reference/configuration-options#lockfilemaintenance) option being enabled by default, yes the [configuration in `renovate`](https://github.com/renovateapp/renovate/blob/116939ffb51d460beffcb206d7e45057adffa0ca/lib/config/definitions.js#L647) is disabled by default.

Furthermore, it's [disabled in `renovate-config`](https://github.com/singapore/renovate-config/blob/master/packages/renovate-config-config/package.json#L28)

**Comment by rarkins** [comment]
Thanks, it's definitely disabled by default (way too much confusion from users when it was enabled automatically). I have fixed the website doc in https://github.com/renovateapp/renovate/commit/6506b39222ac794829345e14743f84ca85e076b4

**Comment by destroyerofbuilds** [comment]
Thank you @rarkins! I'm sorry I couldn't find the website documentation. 😢 Now I know.

**Comment by rarkins** [comment]
It’s not intuitively located but works for now!
