### ISSUE TITLE
branchPrefix is lost

### ISSUE THREAD

**Issue by KnisterPeter** [renovateapp/config-help#14]
I have a `config.js` similar to the one below.
But when an onboarding MR is created it states that the branches will be created as `renovate/...` which is the renovate default.
When updating the `renovate.json` then and add the branchPrefix there, rerunning renovate will update the description of the MR but also overwrite the `renovate.json` back to the default (e.g. remove the branchPrefix).

```js
module.exports = {
    platform: "gitlab",
    branchPrefix: "feature/renovate/"
}
```

**Comment by rarkins** [comment]
I think it’s the config:base preset overriding your bot’s config.js setting. The onboarding PR js currently hardcoded to renovate/configure though.

**Comment by KnisterPeter** [comment]
That may explain it. So I could only have a correct setup using presets?

**Comment by rarkins** [comment]
Don’t use the config:base preset for now in the repo because it includes a sub-preset that is “resetting”/overriding your bot defaults. Longer term fix is for me to fix the preset so that is doesn’t unnecessarily reset to default values.

**Comment by KnisterPeter** [comment]
Thanks
