### ISSUE TITLE
Update one package based on a dist tag

### ISSUE THREAD

**Issue by posva** [renovateapp/config-help#18]
Hello!

I'm trying to trigger a PR everytime a package is updated in a specific npm tag (ex `next`). I'm able to trigger the update only on the package I want for stable releases if a stable version is specified in package.json and also for unstable releases if an unstable version is specified in package.json file.

Is there a way to update the package if it comes from **both** of the tags (eg: `latest` and `next`)

---

The goal is to trigger updates for a library in bigger libraries repositories that rely on it to see if anything breaks (the PR would trigger CI) before releasing a patch to `latest` in npm. These bigger libraries would have configured renovate before

**Comment by posva** [comment]
cc @rarkins

**Comment by rarkins** [comment]
Hi @posva, you should be able to achieve your goal with the `respectLatest` config option. It defaults to `true`, which means it only upgrades a version past the `latest` version if you are *already* past it. In your case, you want to upgrade it past `latest` at any time, so you should set this to `false`.

If you want to do this for a particular package only, then put it in a package rule like so:
```
 "packageRules": [
     {
       "packageNames": ["package-to-test"],
       "respectLatest": false
     }
   ]
```

By the way, it sounds like you might be interested in this idea and your feedback there would be welcome, to firm up the requirements to help make it a "reality": https://github.com/renovateapp/renovate/issues/1453

**Comment by rarkins** [comment]
Also, if you want those "downstream" repositories to *also* get separate PRs when there is a *stable* (i.e. latest) update (i.e. one PR for stable/latest and one for unstable/next) then it might require some more "tricky" configuration - let me know

**Comment by posva** [comment]
Thank you very much. This should do! I didn't see the `respectLatest` option.
I +1 the issue, it would be interesting for us
