### ISSUE TITLE
Directly push `patch` and `minor` to master and create seperate PRs for major updates

### ISSUE THREAD

**Issue by Skaronator** [renovateapp/config-help#2]
I'm trying setup my config to directly push minor and patches to the master branch and creating seperate PRs for each major updates. My renovate.json looks like this:

```json
{
  "automerge": true,
  "automergeType": "branch-push",
  "major": {
    "automerge": false,
    "automergeType": "pr"
  },
  "multipleMajorPrs": true
}
```
Is this looking good? I've change updated config like 20 min ago and nothing happend yet. Are there any logs when using your github app?

(Also wondering why you have a "multipleMajorPrs" and not just a "multiplePrs" inside of the "major", "minor" part.)

**Comment by Skaronator** [comment]
Thanks for your quick and detailed response! I'll try your config and see how it works out.

> Renovate's default behaviour is to offer you at most one minor and one major upgrade, which means v1.1.0 and v3.0.0. If you set multipleMajorPrs to true then you will get PRs for v1.1.0, v2.0.0 and v3.0.0 (3 separate PRs). Hence why it's called mutipleMajorPrs and not multiplePrs - as you already get multiple PRs regardless.

I though it would create a PR for every major upgrade per dependency. So if I've for example:
 * React on 15.4.1 and they released 16.0
 * AWS on 2.13.7 and they release 3.0
it would create 2 seperate PR request and I can merge them manually.

**Comment by rarkins** [comment]
Yes it's also default behaviour to split PRs per-dependency as you want

**Comment by Skaronator** [comment]
Okay cool, thanks!

**Comment by Skaronator** [comment]
Mh still doesn't work as expected. It creates new branches instead of pushing it directly to my master as you can see here:
![image](https://user-images.githubusercontent.com/2886913/32703859-58d56e7e-c7fc-11e7-934a-90b7f4241b5a.png)
![image](https://user-images.githubusercontent.com/2886913/32703864-65af5d08-c7fc-11e7-9b5e-7d1688a43803.png)

**Comment by rarkins** [comment]
Sorry for any confusion. It never just commits *directly* to master. It always creates a branch first, waits for test results, and then pushes the passing commit to master before deleting the branch. It's usually not a good idea to simply push commits directly as you will end up "breaking" your master branch sooner or later, even with minor updates only.

If your repository doesn't have any tests enabled (i.e there's nothing to pass), then you can set this setting to tell Renovate to not wait for any passing tests:

`  "requiredStatusChecks": null`

**Comment by Skaronator** [comment]
Okay seems logical. I'll get test soon™ but using this for now. Thanks though!

**Comment by Skaronator** [comment]
I've finally some tests and removed the `requiredStatusChecks` line but now it won't push any changes to my master branch.
![image](https://user-images.githubusercontent.com/2886913/33306924-dbe9d358-d414-11e7-94c4-f4094009ab9b.png)


I assum renovate create a new branch -> modify the package.json -> test are triggered -> if test are good -> merge but since I have directly push to master there might be a bug?

It should delete the branch after test run complete and push the same change to master to avoid merge commits.

**Comment by rarkins** [comment]
I can take a look at the server logs and see if that gives us enough info to solve it. Please let me know the repository name and which particular dependency/branch you are expecting to have been automerged

**Comment by Skaronator** [comment]
Repo name: `Skaronator/HHB-Frontend`
Mainbranch: `master`
Renovate Branch: `renovate/redux-form-7.x`
Dependency: `redux-form` from `7.1.2` to `7.2.0`

**Comment by rarkins** [comment]
Thanks, I'll get back to you soon. I think I actually broke it yesterday (by inadvertently skipping the automerge check) with this commit: https://github.com/renovateapp/renovate/commit/eabff37a15375973549dc7ec374d30d77900a3c1

**Comment by Skaronator** [comment]
Alright take your time. Thanks!

**Comment by rarkins** [comment]
@Skaronator I think you should find that the `redux-form` branch has now been automerged. It was indeed being prevented by the faulty logic I mentioned above, now fixed and running in the app.

**Comment by Skaronator** [comment]
Yup just saw the commit, awesome! Thanks
