### ISSUE TITLE
Monorepo config inheritance

### ISSUE THREAD

**Issue by abernix** [renovateapp/config-help#23]
This is in regards to a relatively complex inheritance question.

In [this PR](https://github.com/apollographql/apollo-server/pull/924) the package updates which Renovate applied to the `docs/package.json` don't seem to have followed the Renovate rules defined in that same `docs/package.json`'s [`renovate` section](https://github.com/apollographql/apollo-server/blob/2c4af9cfd768bee23c45ee6d6bae76a1762d9a8b/docs/package.json#L24-L26).  That nested `package.json` configuration inherits from [`apollo-docs`](https://github.com/apollographql/renovate-config-apollo-docs/blob/master/package.json), which further inherits from [`mdg-docs`](https://github.com/meteor/renovate-config-mdg-docs/blob/master/package.json), which should have caused the `hexo` package update to be in a [`hexo-related` grouping](https://github.com/meteor/renovate-config-mdg-docs/blob/aad0c1e7904e8855b96327cd5e08690d72e3bbb0/package.json#L27) and should have been [assigned to me (via `assignee`)](https://github.com/meteor/renovate-config-mdg-docs/blob/aad0c1e7904e8855b96327cd5e08690d72e3bbb0/package.json#L18-L20). 

With that expectation explained, the [root directory](https://github.com/apollographql/apollo-server/tree/2c4af9cfd768bee23c45ee6d6bae76a1762d9a8b/) (one level up) of that repository _does_ have [its own `renovate.json`](https://github.com/apollographql/apollo-server/blob/2c4af9cfd768bee23c45ee6d6bae76a1762d9a8b/renovate.json), but I thought that the nested settings (in the `docs/package.json`, as described above) would take precedence, though I don't know specifically in which way.

---

Related feature idea: I'm sure you have visibility into this behind the scenes, but it might be helpful to include some debug information about which rules were traversed in which configurations within the PR (or via a debug link?).  I think a number of my support questions might have been helped or reduced by exposing this information!  (Though your support is always fantastic and considerate of my own failures. 😁).

**Comment by rarkins** [comment]
@abernix renovate config within a nested `package.json` is not supported. If you need config specific to a particular `package.json`, the easiest way to add it would be with `pathRules`. That way you can see your entire config from one location (e.g. the `renovate.json`, or root `package.json`). Please copy/paste contents here if you'd like help or confirmation of the updated config.

Your last points are right too. I plan to enable users to access debug logs via a web interface soon and also a refactor of how we "resolve"/cascade rules so that it will be much easier to understand.

**Comment by rarkins** [comment]
I think the new config would look like this:

```json
{
  "pinVersions": true,
  "semanticCommits": true,
  "depTypes": [{ "depType": "dependencies", "pinVersions": false }],
  "timezone": "America/Los_Angeles",
  "schedule": ["after 10pm and before 5am on every weekday"],
  "rebaseStalePrs": true,
  "prCreation": "not-pending",
  "automerge": "minor",
  "labels": ["tooling", "dependencies"],
  "pathRules": [{
		"paths": ["docs/package.json"],
		"extends": ["apollo-docs"]
	}],
  "packageRules": [
    {
      "packageNames": ["lint-staged"],
      "allowedVersions": "<7"
    }
  ]
}
```

**Comment by abernix** [comment]
Ah, okay! I guess I'm surprised with this behavior since this text at the top of the [Renovate configuration options](https://renovateapp.com/docs/configuration-reference/configuration-options) suggested to me that this was possible:

> This document describes all the configuration options you may configure in a renovate.json file or within a "renovate" section of your package.json. Note that any config in a package.json will apply only to that package file, so this is also one way you can specify different behaviour for different package.json files. Similarly, if you have a monorepo and want your config to apply to all package files then you need to define it in a renovate.json.

My interpretation of this was that the root `renovate.json` would affect all, but you could have `package.json`s defining more specific behavior (and those `package.json` files would be auto-discovered, unless a root `packageFiles` listed specific `package.json` files).

(Though I was looking forward to this as I manage the `docs` folders within many other repositories and had wanted my rules to supersede those higher up (or at least overlap.)

**Comment by rarkins** [comment]
Whoops, that's an old doc I need to fix. This was actually the breaking change in v11: https://github.com/renovateapp/renovate/releases/v11.0.0

> (Though I was looking forward to this as I manage the docs folders within many other repositories and had wanted my rules to supersede those higher up, or at least extend the root configuration within the local scope.)

That should be possible via `pathRules` as well, although not *exactly* that same (technically packageRules are applied after pathRules so you may need to nest packageRules inside pathRules in certain cases). Ask me here if you have any doubts about how to do it.

**Comment by abernix** [comment]
Great! I'll land that with https://github.com/apollographql/apollo-server/commit/9ab276576b59fd1bbe17e4dbe5d4f92122e13b34 and expand once I validate it.  Thanks, as usual, for your help!
