### ISSUE TITLE
Group remaining @types PR's

### ISSUE THREAD

**Issue by ceyhuno** [renovateapp/config-help#25]
I like that `@types/nock` and `nock` are grouped automatically.
But I also want to group all the other `@types` that remain.
When I use `group:definitelyTyped`, `@types/nock` and `nock` becomes seperated.

**Comment by rarkins** [comment]
This may not be easy. The `@types/nock` grouping you see is implicit, so it takes a lower priority than the explicit `group:definitelyTyped` preset.

What you can try is to remove the preset and add an adapted rule of your own that excludes the package names that you don't want included. e.g.

```
      "packageRules": [
        {
          "groupName": "definitelyTyped",
          "packagePatterns": [
            "^@types/"
          ],
          "excludePackageNames": ["@types/nock"]
        }
      ]
```

**Comment by ceyhuno** [comment]
But the `excludePackageNames` will always change depending on if updates for `@types/something` and `something` exist at the same time.

`@types/nock` is in `excludePackageNames` right now because I need to update both `@types/nock` and `nock`. But in the future I may only need to update `@types/nock` and I want then it to be grouped with other `@types/something`s that don't have a `something` update waiting at that moment.

**Comment by rarkins** [comment]
That’s definitely harder! I unfortunately can’t think of any existing configuration trick to achieve it so it may need some code changes

**Comment by rarkins** [comment]
Can you raise it as a feature request in the main repo?

**Comment by ceyhuno** [comment]
👍
