### ISSUE TITLE
Group Docker Digest Updates

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/config-help#26]
This is a follow-up to #24.

How do I group Docker digest updates?

On the `labeledpipe` project, I have a [PR for Docker 4](https://github.com/factset/labeledpipe/pull/58), and a [PR for Docker 6](https://github.com/factset/labeledpipe/pull/57).

Logically, I should be able to group the digest updates into a single PR, and if a single digest is bad, I should see that in the Status Checks (Our Circle CI setup has a status check per Node version, so it's really easy to see which Node version is breaking)

**Comment by rarkins** [comment]
Usually, grouping is controlled by group name, which then translates to branchName to cause the grouping to occur.

In this case your branches are `renovate/docker-node-4` and `renovate/docker-node-6` so instead you would want either `renovate/docker-node` or `renovate/docker-digests` if in theory you want to combine more than just `node`.

Here's one possible way that I tested and seems to work:
```
  "docker": {
    "digest": {
      "groupName": "Docker digests",
      "group": {
        "prTitle": "Update Docker digests"
      },
      "automerge": true
    }
},
```

Replace your existing `digest` object with the above (i.e. nest it inside `docker` and add the group settings).

**Comment by destroyerofbuilds** [comment]
@rarkins your suggestion worked exceptionally well 👍 

Here's our grouped pull request - https://github.com/factset/labeledpipe/pull/59

Here's the specific change I made to our repository for anyone interested - https://github.com/factset/labeledpipe/commit/0a3a1fd6f5e88d23783dc6d5a619d3fda5e3b813
