### ISSUE TITLE
Grouping all updates together but separating major releases at the same time

### ISSUE THREAD

**Issue by LKuechler** [renovateapp/config-help#27]
Hi. First thanks for this cool project :)

I currently try to achieve to have all updates grouped that are not major releases.
This are my current settings for this:
```
{
	"extends": [
		"group:all",
		"schedule:weekly",
		":maintainLockFilesWeekly"
	],
	"separateMajorReleases": true
}

```

If you have a idea how to this can be achieved i would be very grateful for input :)

**Comment by LKuechler** [comment]
`combinePatchMinorReleases` seems to be what i needed :)

**Comment by rarkins** [comment]
Actually `:combinePatchMinorReleases` only refers to the same package, and is the default anyway.

What you want is something more like this:
```
{
	"extends": [
		"schedule:weekly",
		":maintainLockFilesWeekly"
	],
	"minor": {
      "group:all"
    }
}
```

This way the "all" grouping applies only to non-major updates.

**Comment by rarkins** [comment]
But this is probably better/simpler:
```
{
	"extends": [
		"schedule:weekly",
		":maintainLockFilesWeekly"
	],
	"minor": {
      "groupName": "all minor"
    }
}
```

**Comment by LKuechler** [comment]
This works very good thank you :)

I now only have one more problem...
Do you know why it currently sometimes generates commits with the type `fix`?
This is my current config:
```
{
	"extends": [
		"schedule:weekly",
		":maintainLockFilesWeekly",
		":semanticPrefixChore"
	],
	"minor": {
		"groupName": "all minor"
	}
}
```

Exp: `fix(deps): update dependency mobx to v4`
There are also other commits that are correct with the type `chore`

**Comment by rarkins** [comment]
It's a bit complicated. By default we "autodetect" the semantic prefix an use `fix` for `dependencies` because those can change what is published and hence should result in at least a patch release according to semantic versioning.

If you wish to override that and use `chore` for everything, replace `:semanticPrefixChore` with `:semanticCommitTypeAll(chore)`

**Comment by LKuechler** [comment]
makes sense. Thank you for all your help :)
