### ISSUE TITLE
exclude packages

### ISSUE THREAD

**Issue by ahmedelgabri** [renovateapp/config-help#30]
I'm trying to exclude a couple of packages from being updated at all, but I'm not really successful doing this till this moment. Here is the config 

```json
{
  "extends": ["config:base", ":preserveSemverRanges", "schedule:nonOfficeHours"],
  "docker": {
    "enabled": false
  },
  "docker-compose": {
    "enabled": false
  },
  "circleci": {
    "enabled": false
  },
  "nvm": {
    "enabled": false
  },
  "automerge": false,
  "major": {
    "automerge": false
  },
  "pinVersions": true,
  "labels": ["upgrade", "bot"],
  "timezone": "Europe/Amsterdam",
  "excludePackageNames": ["gulp-sass", "node-sass", "jquery", "query-string", "coffee-loader", "sass-loader"]
}
```

I tried `excludePackageNames`, `excludePackagePatterns` both at the root level of the object & inside `packageRules` but none actually worked. I wonder what am I doing wrong here?

**Comment by rarkins** [comment]
Use `"ignoreDeps"` instead of `"excludePackageNames"`. I also recommend simplifying your config as follows:

```
{
  "extends": ["config:base", ":preserveSemverRanges", "schedule:nonOfficeHours"],
  "enabledManagers": ["npm"],
  "pinVersions": true,
  "labels": ["upgrade", "bot"],
  "timezone": "Europe/Amsterdam",
  "ignoreDeps": ["gulp-sass", "node-sass", "jquery", "query-string", "coffee-loader", "sass-loader"]
}
```

automerge is disabled by false, so you do not need to include that.

`":preserveSemverRanges"` and `"pinVersions": false` contradict each other. What exactly do you want?

**Comment by ahmedelgabri** [comment]
Thanks, that's much better! So what is `"excludePackageNames"` is for then?

> `":preserveSemverRanges"` and `"pinVersions": false` contradict each other. What exactly do you want?

I didn't have `"pinVersions": false`? What I want is to always pin the versions.

**Comment by rarkins** [comment]
> So what is "excludePackageNames" is for then?

It's for use within `packageRules`. e.g. you could define a `packagePattern` like `^eslint` but then set `excludePackageNames` to `["eslint-foo"]`.

> I didn't have "pinVersions": false? What I want is to always pin the versions.

Sorry, somehow it got mixed up in my copy/paste. Here's what you probably want then:

```
{
  "extends": [
    "config:base",
    ":pinAllExceptPeerDependencies",
    "schedule:nonOfficeHours"
  ],
  "enabledManagers": ["npm"],
  "labels": ["upgrade", "bot"],
  "timezone": "Europe/Amsterdam",
  "ignoreDeps": ["gulp-sass", "node-sass", "jquery", "query-string", "coffee-loader", "sass-loader"]
}
```

**Comment by ahmedelgabri** [comment]
Thanks!

> It's for use within `packageRules`. e.g. you could define a `packagePattern` like `^eslint` but then set `excludePackageNames` to `["eslint-foo"]`.

One feedback here, is in the [docs](https://renovateapp.com/docs/configuration-reference/configuration-options) maybe you can show the options inside a dummy/demo object so the structure is a bit more clear because it feel like all the options are on the same level. Or maybe mention where they belong in the structure?

**Comment by rarkins** [comment]
FYI I have updated the docs with examples

**Comment by ahmedelgabri** [comment]
Thank you

**Comment by ahmedelgabri** [comment]
BTW, `"enabledManagers": ["npm"],` this doesn't seem to be working as expected. The PR description was updated with stuff for docker, circleci, etc... after I added this line & removed this

```json
  "docker": {
    "enabled": false
  },
  "docker-compose": {
    "enabled": false
  },
  "circleci": {
    "enabled": false
  },
  "nvm": {
    "enabled": false
  },
```

**Comment by rarkins** [comment]
By "PR description" do you mean the onboarding one? That one is auto-generated and far from perfect - it doesn't understand when you "override" config:base functionality. Because Renovate config can be extremely flexible, it also means it would be extremely difficult to accurately "describe" the config.

If you want to depend on the description of the onboarding PR being perfect, then remove `config:base` and instead pick and choose from its list: https://github.com/renovateapp/renovate-config/blob/master/packages/renovate-config-config/package.json#L19-L34

**Comment by ahmedelgabri** [comment]
Good to know, because I was depending a bit on the PR description.
