### ISSUE TITLE
Only run on repos with config

### ISSUE THREAD

**Issue by MarcusNoble** [renovateapp/config-help#31]
I'm trying to run renovate against all repos but filtered to those that have a renovate config specified.

I thought I could do this using `renovate --require-config true --autodiscover` but that doesn't seem to do what I expected. 

Is there any way to target specific repos without having to manually list them all?

**Comment by rarkins** [comment]
Do you mean you have certain repositories that you have manually added a `renovate.json` to, and you want to run only on those?

If so then unfortunately no, there is no option for that. If you run with `--autodiscover` then Renovate will run on all repositories it has write access to and raise a "Configure Renovate" PR on each. If you close the PR unmerged then Renovate will then skip over such a repository.

The option `--require-config` determines whether Renovate skips repositories like described above. If true, then it skips repositories where the onboarding PR was closed unmerged. If false, then it runs anyway.

**Comment by MarcusNoble** [comment]
Ah. That's a shame. 

We currently have too many repos to manually go through and marked which we want set up with renovate. The plan was going to be to add a `renovate.json` to new repos and when we are work on old ones.

**Comment by rarkins** [comment]
What most people do is have a dedicated bot account for Renovate and add it as a collaborator to repositories one by one. The bot can also hold a centralised default config which might be faster than manually adding `renovate.json` to each. The other alternative is to list the repositories in the bot's `config.js` file, if you wish to use a bot account that has wider access than you wish to run Renovate on.

**Comment by rarkins** [comment]
You are welcome to submit a pull request for this feature to the main repo, although please raise an issue first so we can discuss/agree on its naming and requirements for how it should work.

**Comment by MarcusNoble** [comment]
Sure! Let me have a think about it. I'm thinking wrapping it in a little bash script might work just as well for our purpose.

Thanks for such quick responses. 👍
