### ISSUE TITLE
Trouble with rebasing PRs for automerge

### ISSUE THREAD

**Issue by CKarper** [renovateapp/config-help#33]
So, for one test repo we've added Renovate.   We got through the onboarding PR, and Renovate generated 18 follow-on PRs.  The first two automerged successfully on subsequent runs, but it has hung up on the third one.

There is confusing messaging coming from the different log levels.   
* With a normal run, the error says that one of the status' is not `success`, which is not the case.
* With a debug logged run, the error seems to be around a github 405 response when PUT-ing a merge.
* [Full Logs Here](https://gist.github.com/CKarper/7ca0a3ea03bc6ae2fab651cc1906aee2)

The real issue, IMO, is the line incorrectly stating that a rebase is not needed.
```
DEBUG: Branch does not need rebasing (repository=harbour/service-boilerplate-node, dependencies=bluebird, branch=renovate/bluebird-3.x)
```

![image](https://user-images.githubusercontent.com/653156/39052828-40ce2784-447b-11e8-9141-02accb1157d5.png)

I am betting that I could unplug this by just updating the branch manually, but I figured it was a good opportunity to debug the behavior.

**Comment by rarkins** [comment]
That message is printed if Renovate gets a 404 back from GitHub when attempting to query branch protection settings. A 404 is returned if there *are* no branch protection settings, but maybe in this case it could be a permissions problem. Maybe the user account you are running with does not have permissions to view branch protection? Although as humans we can see or infer pretty much all types of branch protection settings from the GitHub Web UI, the GitHub API instead hides branch protection settings for all users except those with admin permissions. This might be the case here. When run as a GitHub App, we request read admin rights for this very reason.

Assuming you don't want to troubleshoot any further, add the preset `:rebaseStalePrs` to our `extends` array to configure manually what Renovate is failing to detect.

**Comment by CKarper** [comment]
I have no problem adding that to the config, as it makes sense for how we want Renovate to work...   That said, I don't mind going down the rabbit hole a little further if it's helpful.

What I found interesting was that it has already merged other PRs, and got them through the rebase/merge steps successfully.   This is the same repo, same user, nothing has changed on that front.

**Comment by rarkins** [comment]
It probably makes some sense:

1. After the onboarding PR, all PRs created would be up to date
2. Renovate would automerge the first PR it finds that has status=success reported by GitHub
3. Immediately after that, all remaining PRs would be stale and not able to merge
4. (I'm guessing) at least one of the remaining PRs were *conflicted*
5. Renovate runs again and rebases the conflicted PRs, making them unstale
6. Renovate merges the first unstale PR that is green
7. Repeat step 4-6 again until there are no conflicts

By configuring `rebaseStalePrs` it means this alternate reality:

4. Renovate will rebase *all* PRs

**Comment by CKarper** [comment]
Ahh, so the difference was conflicted vs stale.  Makes more sense.  

Excellent, then I'll consider this resolved.   Thanks so much for all the additional help!
