### ISSUE TITLE
Link to source for docs

### ISSUE THREAD

**Issue by edmorley** [renovateapp/config-help#4]
Hi!

I was reading this page:
https://renovateapp.com/docs/configuration-reference/config-presets

...and spotted a typo for which I was hoping to open a PR (`s/but adding/by adding/`).

However I can't seem to find a corresponding page on:
https://github.com/renovateapp/renovate/tree/master/docs

Are the docs in another (possibly private) repo? It would be great to have the source for them somewhere contributions can be made, and linked from the docs page.

**Comment by rarkins** [comment]
@edmorley yes, the renovateapp.com site is currently in a private repo, which has the downside that so too are any docs there. I'm thinking of embedding it within the `renovate` repo itself, as that would make it the easiest to keep it up to date with the source and possibly autogenerate/autolint some sections.

Anyway, I have fixed that typo - thanks - so nothing more to do for this issue.
