### ISSUE TITLE
Custom commit message does not work

### ISSUE THREAD

**Issue by wbotelhos** [renovateapp/config-help#7]
Hi,

I'm trying to add `[ci skip]` to commit message, but it is not working. Maybe my syntax?

`renovate.json`:

```
{
  "commitMessage": "{{semanticPrefix}} updates {{depName}} to {{newVersion}} [ci skip]",

  "extends": [
    "config:js-app"
  ],

  "ignoreDeps":     ["danca-guide"],
  "schedule":       ["after 2:00am and before 4:00am"],
  "semanticPrefix": "[ci skip]"
}
```

First I tried `semanticPrefix`, than `commitMessage`, but no effect. :(

Actual message:

`Update ruby to tag 2.5.0-alpine`

**Comment by rarkins** [comment]
@wbotelhos could you try this config instead?
```
{
  "extends": [
    "config:js-app"
  ],
  "ignoreDeps":     ["danca-guide"],
  "schedule":       ["after 2:00am and before 4:00am"],
  "commitBody": "[ci skip]"
}
```

This should append "[ci skip]" to the commit message below the "regular" message, without needing to recreate any existing templates.

**Comment by wbotelhos** [comment]
Thank you so much, @rarkins it worked! \o/

<3
