### ISSUE TITLE
Monorepo with application and libraries

### ISSUE THREAD

**Issue by christopherjbaker** [renovateapp/config-help#9]
Your suggestion is to not pin libraries but to pin applications. (In I don't like pinning, but I see the reasoning.)

However I have a monorepo which contains both, but it seems I can only pin all or not pin all. Ideally, I'd like to pin `./package.json` (potentially a few others) and leave the rest as ranges (alternately, set `./modules/*/package.json` and `./apps/*/packages.json` as ranges, and make the rest pinned).

Is there any kind of support for this kind of split behaviour? Or any chance it could be added?

**Comment by rarkins** [comment]
By default, Renovate "autodetects" whether to pin per-package.json at run-time. The logic is pretty simple and conservative: https://github.com/renovateapp/renovate/blob/367e21ab300e681450ef9207018d2f31812b53bd/lib/workers/package-file/index.js#L14-L27

So ideally it should be able to determine which of your package.json's are libraries and leave them unpinned. If that's not the case and you think the *logic* can be improved, please let me know.

If you wish to force configure it by path, you can use `pathRules`. e.g. I think something like this should work:

```json
{
  "extends": ["config:base", ":pinVersions"],
  "pathRules": [
    {
      "paths": ["modules/*/package.json", "apps/*/packages.json"],
      "extends": [":pinOnlyDevDependencies"]
    }
  ]
}
```

We use `minimatch` for glob matching of `paths`. I'm not 100% sure if the `./` prefix is correct or not for our use case, you may need to drop it to get it to work.
